-- Table: public.source_data_eur

-- DROP TABLE IF EXISTS public.source_data_eur;

CREATE TABLE IF NOT EXISTS public.source_data_eur
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    upload_dt timestamp without time zone NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL,
    rate numeric(10,4) NOT NULL,
    CONSTRAINT source_data_eur_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.source_data_eur
    OWNER to airflow;